# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  

steps:

- task: NuGetCommand@2
  inputs:
    command: 'restore'
    restoreSolution: '**/*.sln'
    feedsToUse: 'select'
    vstsFeed: 'c96d8799-9382-482e-a096-4b4840c12500/2773aa61-df41-45ce-8df3-ea6af9323a4c'
    
- task: DotNetCoreCLI@2
  displayName: 'dotnet build'
  inputs:
    command: 'build'
    projects: '**/*.csproj'
        
- task: DotNetCoreCLI@2
  displayName: 'dotnet pack'
  inputs:
    command: pack
    packagesToPack: '**/*.csproj'
    nobuild: true
    versioningScheme: byBuildNumber

- task: NuGetCommand@2
  displayName: 'push'
  inputs:
    command: 'push'
    feedsToUse: select
    packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: 'c96d8799-9382-482e-a096-4b4840c12500/2773aa61-df41-45ce-8df3-ea6af9323a4c'
    allowPackageConflicts: true
    versioningScheme: off 

