name: 1.0.$(rev:r) 

trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  

steps:
    
- task: DotNetCoreCLI@2
  displayName: 'dotnet build'
  inputs:
    command: 'build'
    projects: '**/*.csproj'
    arguments: '--configuration $(BuildConfiguration)' 
        
# Package a project
- task: NuGetCommand@2
  inputs:
    command: 'pack'
    configuration: $(BuildConfiguration)
    packagesToPack: '**/*.csproj'
    packDestination: '$(build.artifactStagingDirectory)'
    versioningScheme: byBuildNumber

- task: NuGetCommand@2
  displayName: 'push'
  inputs:
    command: 'push'
    feedsToUse: select
    packagesToPush: '$(build.artifactStagingDirectory)/$(ProjectName)*.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: 'c96d8799-9382-482e-a096-4b4840c12500/2773aa61-df41-45ce-8df3-ea6af9323a4c'
    allowPackageConflicts: true
    versioningScheme: off 

